spring:
  profiles:
    include: API-KEY

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tothemoon?serverTimezone=Asia/Seoul
    username: tothemoon
    password: passwd123

  jpa:
    hibernate:
      ddl-auto: update     # create - 애플리케이션 실행 시점에 내가 가지고 있는 테이블을 다 지우고 재 생성. / none - 안 지우고 계속 사용
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true     #system.out.print로 출력하는 것
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  logging:
    level:
      org.hibernate.SQL: debug                #log출력.
      org.hibernate.type: trace

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1006923698008-cjvmqlsnjln7hfjf7aavhiku9nq19q59.apps.googleusercontent.com
            client-secret: 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
            scope: email
          naver:
            client-id: vuSiRdORSevC8gFmypXd
            client-secret: M2ghFvpaez
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: email
            client-name: Naver
            client-authentication-method: POST
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
